### ISSUE TITLE
theme: add version selector

### ISSUE THREAD

**Issue by Nuc1eoN** [McShelby/hugo-theme-relearn#1050]
Greetings again, I hope you are doing well! :)

We at GoboLinux have been considering a feature for our wiki in which we could select the documentation content based on the released version.

For instance it would be useful to access the documentation of GoboLinux 017 once 020 is released, eihter because people might still be on 017 or just due to archival reasons for future generations.

Nowadays it seems to have become common to have a selector similar to this:

![Image](https://github.com/user-attachments/assets/6fc767dc-b8ac-4a10-8862-27f68b5fff8d)
(example from docosaurus)

I would imagin two ways of going about it: a) is a selector based on a git branch, b) is a selector based on a git version tag (personally I would probably prefer this as  it might be more comfortable to manage)

I wonder would such a feature be feasable for the hugo relearn theme?

What are your thoughts on this @McShelby ?

Best wishes!

**Comment by McShelby** [comment]
Hi Nuc1eoN, long time not heard of you! Much has happened in the meantime.

I've done my fair share of research for this issues (meaning: spying at other themes).

Representation seems to be the easiest part. Something like this?

![Image](https://github.com/user-attachments/assets/006f0681-fd30-4b7c-bf5f-8fed5e687b4c)

![Image](https://github.com/user-attachments/assets/ae2867c2-74fc-4b13-a054-2bc76901a83e)

For configuration, I would propose Hugos menu feature. [Since version 7.1.0 the sidebarmenu is configurable](https://mcshelby.github.io/hugo-theme-relearn/configuration/sidebar/menus/index.html#defining-sidebar-menus). For the version selector, I would replicate this mechanism but for the sidebarheader. A new parameter `visual` will allow the values `tree` (the current way of displaying menus) and `selectbox' (resulting in the visual shown above).

Pros:
- easy to implement
- each version is generated completly independend of other versions by issuing `hugo` for each. You would be responsible to feed the correct source files to Hugo.

Cons:
- can only link to the main page of this version instead of linking to the same page but for that version
- configuration of older versions need to be adapted and a rebuild would be necessary if older versions should reference newer versions in their version select box.

What do you think?

**Comment by Nuc1eoN** [comment]
Hi, thanks for coming back to me so quickly. To me it sounds good!

My first thought was having it in the topbar on the right, but I think it being in the sidebar is a good idea as well! I think I like it.

Would it be possible to select the position in the sidebar, eg bottom left or at the top like in your screenshot? I am not yet sure whether I want it to be "in your face" or just a discreet option in the corner... In any case your example looks quite good :)




> Pros:
> 
> * easy to implement
> * each version is generated completly independend of other versions by issuing `hugo` for each. You would be responsible to feed the correct source files to Hugo.

Sounds all good to me.


> Cons:
> 
> * can only link to the main page of this version instead of linking to the same page but for that version

That kinda makes sense, since we cannot know whether a certain page has been removed or exists in another version. I don't know how it would be possible to solve that... Unless the solution would first "try" whether the same site exists in the other version (maybe upon clicking it and client-side) and if it doesn't exist then direct to the main page.

Probably this isn't even possible to implement, but I am just putting it out :D How do other static doc solutions deal with it??

In any case, it is not a deal breaker!! :)

> * configuration of older versions need to be adapted and a rebuild would be necessary if older versions should reference newer versions in their version select box.

Ohh I see! I think that is expected.


To me it all sounds good, albeit I don't know what an alternative approach could look like.

All in all still green light from my side 👍

**Comment by McShelby** [comment]
I am still thinking about the implementation.

I am hoping to do some tricks, to lift the necessity to rebuild old versions just to make newer versions known to their version selector.

Putting this switch in the menu footer shouldn't make much of a difference than putting it into the menu header.

Having that switch in the topbar is a different thing. For the initial implementation, I would skip that.

Anyways, this can take quite a while before I can implement it. Currently my focus is on the search feature and also real life is keeping me busy, too.

**Comment by Nuc1eoN** [comment]
Oh no haste! Thank you for considering it for the future :)

If I can give an advice, I think having a useful feature with rough edges is better than not having it at all. So going step by step should make it less of a burden hopefully.

> I am hoping to do some tricks, to lift the necessity to rebuild old versions just to make newer versions known to their version selector.

This is something that could be done in later versions imo, I see it more as an optimizion. Personally I am fine even with rebuilding it.

> Having that switch in the topbar is a different thing. For the initial implementation, I would skip that.

Yeah and I think the sidebar is better, maybe unless someone requests it to be in the topbar in the future.

**Comment by McShelby** [comment]
I laid out the ground work in #1059 and #1057. This will come with 7.6.0

**Comment by McShelby** [comment]
Done. See docs here: https://mcshelby.github.io/hugo-theme-relearn/configuration/sitemanagement/versioning/index.html

By default, the version selector is displayed in the menu header. If you want to reposition it to the footer, the theme got you covered as well http://localhost:1313/configuration/sidebar/menus/#defining-sidebar-menus

Would be great to get feedback on this.

Also letting you know that this "trick" is implemented

> some tricks, to lift the necessity to rebuild old version

**Comment by McShelby** [comment]
You only have to move your files to `assets` if they were overriding existing files of the theme. Otherwise better leave them in `static`.

How are you applying your fonts to the themes CSS. There are multiple variants while the easiest would (probably) be to just set the `-MAIN-font` & friends CSS variables.

**Comment by Nuc1eoN** [comment]
Yes, I am defining my fonts like so:

```css
--MAIN-font: "Public Sans"; /* Font family of main content */
--MAIN-TITLES-TEXT-font: "Metropolis"; /* Font family of headlines */
```

According to the inspector these are getting applied correctly:

![Image](https://github.com/user-attachments/assets/329331b2-8eef-428d-ac50-a7f299b58db3)

![Image](https://github.com/user-attachments/assets/18b53438-6a4e-406a-9321-e90dfbe22910)

I have my fonts under `/static/fonts`. And I am setting them up like this in the gobolinuxc css theme:
```css
/* Headline font */
@font-face {
    font-family: "Metropolis";
    font-style: normal;
    font-weight: 500;
    src: url("/fonts/metropolis-bold-webfont.woff2") format("woff2");
    font-display: swap;
}

```

These font files correctly get copied over to the `public/fonts/` dir:

![Image](https://github.com/user-attachments/assets/f396fad0-9759-450c-8eff-381cce6f9c83)

But they are missing from in the sources( Inspector -> Sources) of the actual hosted site, the reasons are unclear to me:

![Image](https://github.com/user-attachments/assets/e64af8fe-88be-43a3-bc81-8dfc78bfd908)

**Comment by McShelby** [comment]
Are your changes public, so I can take a look into it?

**Comment by McShelby** [comment]
Okay... now I got it. Stay tuned...

**Comment by McShelby** [comment]
Because of the way, the theme variant file is now processed, you need to put all your `@font-face` settings into `assets/css/fonts.css`. A fact worth mentioning in the docs.

**Comment by Nuc1eoN** [comment]
Great that did it! Indeed I was looking through the documentation and breaking changes but could not find any reference to font customization.

I'll continue porting and will come back to you when I am finished and can finally test the version switcher 😃 

Eins vorweg: The deprecation warnings you've introduced are super helpful! What is not helpful though, is that no single link referencing the docs still worked :D Just pointing it out. I was able to solve these issues.

Also, as pointed out by one the warning messages, I have ported all reflinks from eg `{<ref "Installing GoboLinux" >}}` to `{{%ref "Installing GoboLinux" %}}`. Which generally works, but for some reason some of those links now get opened in a new tab (even though they are internal links) 🤔
Upon checking they now contain the `rel="external" target="_blank"` attributes. Any clue why? If you want I can share my current code with you. But basically you can take the current site, go https://wiki.gobolinux.org/Commands/Installer/index.html and change the link on this page to be enclosed by `% ... %` rather than `< ... >`. Is that change expected?

BTW: Hast du eine PayPal email adresse? (habe meine GitHub Zahlungen hier noch nicht aufgesetzt)

**Comment by McShelby** [comment]
> Eins vorweg: The deprecation warnings you've introduced are super helpful! What is not helpful though, is that no single link referencing the docs still worked :D Just pointing it out. I was able to solve these issues.

Just checked your repo with the commit I mentioned above. There seem only to be two warnings with links and both them work by clicking in my VS Code terminal. Namly these were the warnings:

> WARN  DEPRECATED usage of 'params.author' config parameter found, replace it with `params.author.name` in your hugo.toml; see https://mcshelby.github.io/hugo-theme-relearn/introduction/releasenotes/5/#5-23-0

> WARN  UNSUPPORTED usage of 'params.description' config parameter found, move it to the front matter of your home page; see https://mcshelby.github.io/hugo-theme-relearn/introduction/releasenotes/6/#6-0-0

The warnings about the `relref` call syntax do not have documentation as this behavior was always present but no will be recognized by the theme. This is due to the way Hugo works

> WARN  "C:\\Daten\\Sören\\git\\gobolinux-documentation\\content\\Howtos\\SandboxInstall-Howto.md": WARNING you must call the ref / relref shortcode with '% %' instead of '< >' to work correctly for the anchor target attribute

> Also, as pointed out by one the warning messages, I have ported all reflinks from eg `{<ref "Installing GoboLinux" >}}` to `{{%ref "Installing GoboLinux" %}}`. Which generally works, but for some reason some of those links now get opened in a new tab (even though they are internal links) 🤔

So, a few thing involved here. `ref/relref` is obsolete nowadays. You should switch to plain Markdown links. Nevertheless, the shortcodes still work but behave a bit different. When invoking  the `relref` shortcode a relative link will be sent to the themes link render hook while `ref` sends an absolute link (containing the `http://` part and your server address). Upon checking they now contain the `rel="external" target="_blank"` attributes. Any clue why? If you want I can share my current code with you. But basically you can take the current site, go https://wiki.gobolinux.org/Commands/Installer/index.html and change the link on this page to be enclosed by `% ... %` rather than `< ... >`. Is that change expected?

When the theme sees the `http://` it assumes it is an external link. It does not check the server address, as this is errorprone in Hugo. So the short solution for you would be to change from `ref` to `relref`.

Another solution would be to turn off the special treatment of external link addresses globally by setting `externalLinkTarget=_self` or overwrite it individually [for each link](https://mcshelby.github.io/hugo-theme-relearn/authoring/frontmatter/linking/index.html#opening-links)



> BTW: Hast du eine PayPal email adresse? (habe meine GitHub Zahlungen hier noch nicht aufgesetzt)

Didn't know you're a german guy. Or are you just trying to be polite 😄

Paypal traue ich nicht von hier bis zur Wand. Bisher nur GitHub-Sponsoring - und das auch nur weil schon so viele gefragt haben.

**Comment by Nuc1eoN** [comment]
> Can you point me to the warnings with invalid links?

My logs are gone but I will try to replicate and send it to you.

> So, a few thing involved here. ref/relref is obsolete nowadays. You should switch to plain Markdown links.

Really? Markdown is preferred? But I cannot make a nice wildcard link like with relref can I? For instance `{{<ref "Installing-Gobolinux" >}}` will always resolve to the correct page, as long as the file name stays the same, but it does not matter which directory it is in. But with markdown don't I have to specify a full path? I think that would be more error prone when shuffling around the structurre/directores...

> When the theme sees the http:// it assumes it is an external link. It does not check the server address, as this is errorprone in Hugo. So the short solution for you would be to change from ref to relref.

Makes sense, ty!

> Didn't know you're a german guy. Or are you just trying to be polite 😄

> Paypal traue ich nicht von hier bis zur Wand. Bisher nur GitHub-Sponsoring - und das auch nur weil schon so viele gefragt haben.

Wirklich? Ich dachte das wusstest du! :D Aber das heißt ich bin hier gut getarnt unterwegs hehe.

Tatächlich hatte nie probleme mit PayPal! Schick mir mal einfach deine IBAN auf meine E-Mail: nuc1eon@neonsys.org. Mag sich altmodisch anhören aber ich gebe mein Kontodaten nicht an M$ solange ich es nicht muss 😅

**Comment by McShelby** [comment]
> Markdown is preferred? But I cannot make a nice wildcard link like with relref can I? For instance {{<ref "Installing-Gobolinux" >}}

Yeah. That's the limitation were behavior differs. But I would bet, 5 years from now and the ref/relref shortcode ain't no more.

> But with markdown don't I have to specify a full path?

You could also use relative paths based on the current page.

I would strongly recommend to add `link.errorlevel="warning"` & [friends](https://mcshelby.github.io/hugo-theme-relearn/authoring/frontmatter/linking/index.html#enabling-link-and-image-link-warnings) to your configuration to find invalid links early.

> Aber das heißt ich bin hier gut getarnt unterwegs hehe.

Jetzt nimmer 😄  Auch aus den Folgelinks zu GoboLinux konnte ich auf die Schnelle nicht erkennen, dass es da einen Bezug zu Deutschland gibt. 

> Schick mir mal einfach deine IBAN auf meine E-Mail

Werde ich machen. Danke für die Unterstützung.

**Comment by Nuc1eoN** [comment]
Greeting! I am now trying to implement the versisoning. Atm I am unclear about this instruction:
> 3. Copy you Hugo project into a new directory

Copy in where and in what directory? I am unclear how those two versions of the site will connect 🤔 Maybe in your steps you could give an example how it is done. (I know that is what you tried to do but for me it is not clear enough 😄).

Also how will this interplay with automatic deployment. We are using: https://github.com/gobolinux/Documentation/blob/master/.github/workflows/hugo.yml

I suppose it will need adjustment to auto generate this? I think we do not need to re-generate old version all the time, but they will have to be generated at least once 🤔

**Comment by McShelby** [comment]
All valid points, I'll update the docs later.

**Comment by McShelby** [comment]
I've pushed a revised version at the same location. Please review and tell me if anything needs clarification.

**Comment by McShelby** [comment]
Setup looks good to me. I'll take a look into it. Stay tuned.

**Comment by McShelby** [comment]
I've pushed a patch that fixes this issues for the default language of a project. For further languages I have to think about it.

**Comment by Nuc1eoN** [comment]
@McShelby Thanks that resolved it!

I am hitting a bug (?) now which I think is unrelated to the versioning functionality though.

On my 'old' site which is under `http://localhost:1314/v017/` the fonts fail to load. Similar to the font bug I had before, the fonts do not get loaded into the hosted site - but this time obviously I have `fonts.css` properly configured just like on my 'new' (main) site.
For reference like so:
```css
@font-face {
    font-family: "Public Sans";
    font-style: normal;
    font-weight: 300;
    src: url("/fonts/PublicSans-Light.woff2") format("woff2");
    font-display: swap;
}
```
I tried changing it to `fonts/PublicSans-Light.woff2` or `/017/fonts/PublicSans-Light.woff2` as well but to no avail.

It is getting late late, I will continue my testing tomorrow. Thanks so far.

**Comment by McShelby** [comment]
I am taken a further look into your "bug" tomorrow.

Just have fixed the version switch for multilang configs now, too.

**Comment by Nuc1eoN** [comment]
I still experience the font thing, but unrelated to that, I tried to play around with the sidebar in order to put the version selector at the bottom.

For this, I have for now simply copied your example from the docs into my `config.toml`:
```toml
[[sidebarfootermenus]]
  type = 'divider'

[[sidebarfootermenus]]
  type = 'custom'

  [[sidebarfootermenus.elements]]
    type = 'historyclearer'

  [[sidebarfootermenus.elements]]
    type = 'variantswitcher'

  [[sidebarfootermenus.elements]]
    type = 'languageswitcher'
```

However there is no change at all on my local site. The sidebar looks just as before. Am I missing something in my config?

PS: You *might* want to add `type = 'versionswitcher'` to the above example as well. `versionswitcher` is only mention below under https://mcshelby.github.io/hugo-theme-relearn/configuration/sidebar/menus/index.html#custom (which is fine I guess, but personally I found it only on the second/third glance)

**Comment by McShelby** [comment]
> However there is no change at all on my local site. The sidebar looks just as before. Am I missing something in my config?

That's the default config. If you want the version switcherin the footer as well, add

````
  [[sidebarfootermenus.elements]]
    type = 'versionswitcher'
````

This will still cause the version switcher to also be displayed in the `sidebarheadermenus`. So you most likely will have to redefine it as well.

For your info:

I am pretty sure that the switchers will have issues if you display each one them more than once on the page. Most likely only the first will work correctly. This will be fixed.

From the docs:
> However, if you decide to overwrite these options, the configuration for those features will not be taken into account anymore. 

I plan to lift this limitation as it will lead to a somewhat unexpected behavior. Although logical in itself, I think the user would expect the eg. the version switcher only to appear if versions are configured - regardless if he's using an unmodified configuration or has given a custom one.

**Comment by Nuc1eoN** [comment]
> That's the default config. If you want the version switcherin the footer as well, add
> ```
>   [[sidebarfootermenus.elements]]
>     type = 'versionswitcher'
> ```
> This will still cause the version switcher to also be displayed in the sidebarheadermenus. So you most likely will have to redefine it as well.

Maybe it is the default config but as mentioned in the docs:

> ...and no multilingual configuration is configured, the language switcher will be shown non the less.

Our wiki currenlty has only a single language, but a laguage selector should be displayed non-the less.
I have also added 
```
  [[sidebarfootermenus.elements]]
    type = 'versionswitcher'
```
But nothing changes!

If you want you can test it here https://github.com/Nuc1eoN/Documentation-Gobolinux/tree/test

**Comment by McShelby** [comment]
I'll take a look into it in the evening.

**Comment by McShelby** [comment]
>

The sidebar config needs to go below the `[params]` key.

So move your sidebar defintions up to line 37 and repharse it like 

````toml
[[params.sidebarfootermenus]]
  type = 'custom'

  [[params.sidebarfootermenus.elements]]
    type = 'languageswitcher'

  [[params.sidebarfootermenus.elements]]
    type = 'historyclearer'
  
  [[params.sidebarfootermenus.elements]]
    type = 'versionswitcher'

[[params.sidebarheadermenus]]
  type = 'divider'

[[params.sidebarmenus]]
  type = 'page'
`````

I'll revise the docs in #1064 to make this clearer and consistent.

**Comment by McShelby** [comment]
Regarding your fonts: Best to reference other files relativley. By that your configuration will work for both, the current version and any archived version. Just add a `..` in front of the `src` properties in your `static/fonts.css` like:

````css
    src: url("../fonts/PublicSans-Light.woff2") format("woff2");
````

**Comment by McShelby** [comment]
I like what you've done with the version selector!

**Comment by Nuc1eoN** [comment]
>The sidebar config needs to go below the [params] key.
>
>So move your sidebar defintions up to line 37 and repharse it like

Good stuff it worked! I must say I am a little bit behind in knowledge when it comes to the hugo stuff.

>Regarding your fonts: Best to reference other files relativley. By that your configuration will work for both, the current version and any archived version. Just add a .. in front of the src properties in your static/fonts.css like:

That did it for both versions indeed! Thanks.

> I like what you've done with the version selector in the menu header!

Thanks, I sketched it up real quick just for testing, but looks like I am gonna keep it 😄 


Ok now I am set up 😸 

Now to the remaining bugs!:

1. The version switcher currrently only works from the homepage, but not from subpages (links to the wrong url). From subpages it routes incorrectly for example to `http://localhost:1314/v017Overview/index.html`

2. In the archived version the URL in the deprecetion is still wrong and point to `http://localhost:1313/v017/index.html` instead of `http://localhost:1313/index.html`

**Comment by McShelby** [comment]
The first one, I found by myself, but I missed the second one.

Both fixed now.

**Comment by Nuc1eoN** [comment]
Thanks as well! 

Would you mind adding a dedicated class to the deprecation warning so that it can be styled independently? Or maybe even make it a partial so that it can be fully customized.

Also this sentence is missing a dot at the very end (I think):
> You are reading version 017 of this page. The current version can be found here

**Comment by McShelby** [comment]
> Would you mind adding a dedicated class to the deprecation warning so that it can be styled independently? Or maybe even make it a partial so that it can be fully customized.
> 
>Also this sentence is missing a dot at the very end (I think):

Both fixed, [read the docs](https://mcshelby.github.io/hugo-theme-relearn/configuration/sitemanagement/versioning/index.html#adjusting-the-versioning-warning)

> Btw, I have just re-generated my archived site without setting relativeURLs = false - everything works just as before and I see no problem with routing... Is this certainly needed? And for what? Thanks in advance.

You need `relativeURLs=true` only if you want to uses your docs [serverless](https://mcshelby.github.io/hugo-theme-relearn/configuration/sitemanagement/deployment/index.html#file-system) from the file system (using `file://`). Otherwise it is better to stay with Hugo's default (which is `false`).

> It seems to me that the only part of the website actually necessary for versioning is the content folder. So I wonder would it work to have a second content folder, eg content-017 or content/versions/017 which contains an old version, and upon generation hugo would be instructed to build content with the apex domain, and content-017 under its 017/ subfolder/subdomain.

If you don't fiddle around with mounts, this still would require a run of `hugo` per each content dir. The resulting pages would still be independend of one another. So if it is your goal to have archived content dirs in parallel to the latest, this is perfectly doable. It's all about your workflow here.

If your goal is, to only run `hugo` once to regenerate _everything_, this is not possible with the implemented solution and I don't find this preferable because:

- all archived versions would be available for search, which will result in multiple hits for a search term
- build times will increase over time as you are always building the archived versions as well

Building the archived versions because the theme or your theme modifications changed, should be a choice and not a necessity and so is also part of the user's workflow.

**Comment by Nuc1eoN** [comment]
> Both fixed, [read the docs](https://mcshelby.github.io/hugo-theme-relearn/configuration/sitemanagement/versioning/index.html#adjusting-the-versioning-warning)

Great stuff thanks!

> You need `relativeURLs=true` only if you want to use your docs [serverless](https://mcshelby.github.io/hugo-theme-relearn/configuration/sitemanagement/deployment/index.html#file-system) from the file system (using `file://`). Otherwise it is better to stay with Hugo's default (which is `false`).

Oh I see! It seems I have mis-understood your docs then, in that a web server from root needs a different `relativeURLs` setting than a webserver run from a subdomain https://mcshelby.github.io/hugo-theme-relearn/configuration/sitemanagement/deployment/index.html#public-web-server-from-root. But it seems you have only been explicit about `relativeURLs = false` in the second example, to note that `relativeURLs = true` is not allowed for subdomains 😅 . In our case obviously we do not plan to run it on the file system.

> If you don't fiddle around with mounts, this still would require a run of `hugo` per each content dir. The resulting pages would still be independend of one another. So if it is your goal to have archived content dirs in parallel to the latest, this is perfectly doable. For this to work, you'll need to adjust your `hugo.toml` for the archived versions which can be done using the `environment` switch for hugo. It's all about your workflow here.

Thank you for pointing that out! I will have to think about it and see whether this is more feasable than having a separate git branch for the archive version (which is what I was about to do). See below.

> If your goal is, to only run `hugo` once to regenerate _everything_, this is only possible with massive adjustments to your config and the front matter (no details here, as I am only thinking about it) and I don't find this preferable because:
> 
> * all archived versions would be available for search, which will result in multiple hits for a search term
> * build times will increase over time as you are always building the archived versions as well
> 
> Building the archived versions because the theme or theme modifications changed, should be a choice and not a necessity and so it is also part of the user's workflow.

I see all valid points. The purpose was not _specifically_ to run hugo only once. Even if that would have been a side effect. The main goal would have been, that all theme updates would apply to the archived version as well, so that the user experience of navigating the docs is streamlined.

For instance, since I am was still working on the theme, I was seeing myself editing the current version and them copy-and-pasting my modifications to the archived versions as well. Esp. because I was playing with the positioning of the version selector while simultaneously testing the versioning functionality :D.

In a usual scenario it would obviously not be, since bad as these theme changes would be less frequent and less severe.

However it highlights, that one version can potentially become "out-of-sync" with the other version, if neglected. And this syncing would take manual work. While also noticing, that theoretically it would be desirable to always have the theme in sync, and only the content being different.

However maybe as you've indicated, that might only be a matter of workflow... I will look into the solutions you have suggested above, as I haven't yet fully wrapped my mind about it ^_^

**Comment by McShelby** [comment]
@Nuc1eoN FYI, I removed the limitation. Now user defined configuration in the `hugo.toml` will behave the same as the default config. So if you explicitly define a language switcher while no languages are configured, there will be no language selector consistently.

> >  However, if you decide to overwrite these options, the configuration for those features will not be taken into account anymore.
>
> I plan to lift this limitation as it will lead to a somewhat unexpected behavior. Although logical in itself, I think the user would expect the eg. the version switcher only to appear if versions are configured - regardless if he's using an unmodified configuration or has given a custom one.

**Comment by McShelby** [comment]
@Nuc1eoN Expect some changes here as Hugo itself is in the final phase of finishing up their own idea of versioning. I am not yet into it, so don't know myself what to expect.
